/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import model.Admin;
import niti.PokreniServer;

/**
 *
 * @author vldmrk
 */
public class ServerskaForma extends javax.swing.JFrame {

    private Admin ulogovan = Controller.getInstance().getUlogovan();
    private PokreniServer ps = new PokreniServer();

    /**
     * Creates new form LoginForma
     */
    public ServerskaForma() {
        initComponents();
        pokreni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdmin = new javax.swing.JLabel();
        jButtonPokreniSrv = new javax.swing.JButton();
        jButtonZaustaviSrv = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAdmin.setText("jLabel1");

        jButtonPokreniSrv.setText("POKRENI SERVER");
        jButtonPokreniSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokreniSrvActionPerformed(evt);
            }
        });

        jButtonZaustaviSrv.setText("ZAUSTAVI SERVER");
        jButtonZaustaviSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZaustaviSrvActionPerformed(evt);
            }
        });

        jButton1.setText("UNESI KORISNIKA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(jButtonPokreniSrv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonZaustaviSrv, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZaustaviSrv)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAdmin)
                        .addComponent(jButtonPokreniSrv)))
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPokreniSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniSrvActionPerformed
        ps.start();
        jButtonPokreniSrv.setEnabled(false);
        jButtonZaustaviSrv.setEnabled(true);
    }//GEN-LAST:event_jButtonPokreniSrvActionPerformed

    private void jButtonZaustaviSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZaustaviSrvActionPerformed
        ps.zaustaviServer();
        jButtonZaustaviSrv.setEnabled(false);
        jButtonPokreniSrv.setEnabled(true);
    }//GEN-LAST:event_jButtonZaustaviSrvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UnesiUsera uu = new UnesiUsera(this, rootPaneCheckingEnabled);
        uu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPokreniSrv;
    private javax.swing.JButton jButtonZaustaviSrv;
    private javax.swing.JLabel jLabelAdmin;
    // End of variables declaration//GEN-END:variables

    private void pokreni() {
        jLabelAdmin.setText("Admin :" + ulogovan.toString());
        jButtonZaustaviSrv.setEnabled(false);
        jButtonPokreniSrv.setEnabled(true);
    }
}
